import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { sprinklesTailwind as st, srOnly } from '../styles/sprinkles.css';
import { fontWeight } from '../styles/typography.css';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className = {
        st({
          display: 'flex',
          justifyContent: 'center',
        })
      }>
        <h1>
          Tailwind Sprinkles
        </h1>
        <div 
        className = {
          st({
            display: 'flex',
            fontFamily: 'sans-serif'
          })
        }>
          <div 
            className = {
              st({
                flex: 'none',
                width: 'size-13',
                position: 'relative',
              })
            }>
            <img src="/jacket.jpg" alt="" 
            loading="lazy" className = {
              st({
                position: 'absolute',
                width: 'full',
                height: 'full',
                objectFit: 'cover',
                inset: '0'
              })}/>
          </div>
          <form 
            className = {
              st({
                flex: 'auto',
                padding: 'size-5',
              })
            }>
            <div
              className = {
                st({
                  display: 'flex',
                  flexWrap: 'wrap'
                })
              }>
              <h1
                className = {
                  st({
                    flex: 'auto',
                    fontSize: 'font-size-3',
                    lineHeight: 'font-lineheight-4',
                    fontWeight: 'font-weight-6',
                    color: 'gray-9'
                  })
                }>
                Classic Utility Jacket
              </h1>
              <div 
                className = {
                  st({
                    fontSize: 'font-size-3',
                    lineHeight: 'font-lineheight-4',
                    fontWeight: 'font-weight-6',
                    color:  'gray-6'
                  })
                }>
                $110.00
              </div>
              <div className = {
                st({
                  width: 'full',
                  flex: 'none',
                  color:  'gray-7',
                  fontWeight: 'font-weight-5',
                  fontSize: 'font-size-0',
                  lineHeight: 'font-lineheight-0',
                  marginTop: 'size-2'
                })
              }>
                In stock
              </div>
            </div>
            <div 
              className = {
                st({
                  display: 'flex',
                  marginTop: 'size-4',
                  marginBottom: 'size-6',
                  paddingBottom: 'size-6',
                  borderColor: 'gray-2',
                  borderBottomWidth: 'border-size-1',
                  alignItems: 'baseline'
                })
              }>
              <div 
                className = {
                  st({
                    display: 'flex',
                    fontSize: 'font-size-0',
                    lineHeight: 'font-lineheight-0',
                  })
                }>
                <label>
                  <input 
                    className = { srOnly }  name="size" type="radio" value="xs" checked />
                  <div
                    className = {
                      st({
                        width: 'size-7',
                        height: 'size-7',
                        borderRadius: 'radius-4',
                        display: 'flex',
                        color: 'gray-7',
                        justifyContent: 'center',
                        alignItems: 'center'
                      })
                    }>
                    XS
                  </div>
                </label>
                <label>
                  <input className = { srOnly } name="size" type="radio" value="s" />
                  <div 
                    className = {
                      st({
                        width: 'size-7',
                        height: 'size-7',
                        borderRadius: 'radius-4',
                        display: 'flex',
                        color: 'gray-7',
                        justifyContent: 'center',
                        alignItems: 'center'
                      })
                    }>
                    S
                  </div>
                </label>
                <label>
                  <input className = { srOnly } name="size" type="radio" value="m" />
                  <div 
                    className = {
                      st({
                        width: 'size-7',
                        height: 'size-7',
                        borderRadius: 'radius-4',
                        display: 'flex',
                        color: 'gray-7',
                        justifyContent: 'center',
                        alignItems: 'center'
                      })
                    }>
                    M
                  </div>
                </label>
                <label>
                  <input className = { srOnly } name="size" type="radio" value="l" />
                  <div 
                     className = {
                      st({
                        width: 'size-7',
                        height: 'size-7',
                        borderRadius: 'radius-4',
                        display: 'flex',
                        color: 'gray-7',
                        justifyContent: 'center',
                        alignItems: 'center'
                      })
                    }>
                    L
                  </div>
                </label>
                <label>
                  <input className = { srOnly } name="size" type="radio" value="xl" />
                  <div 
                     className = {
                      st({
                        width: 'size-7',
                        height: 'size-7',
                        borderRadius: 'radius-4',
                        display: 'flex',
                        color: 'gray-7',
                        justifyContent: 'center',
                        alignItems: 'center'
                      })
                    }>                 
                    XL
                  </div>
                </label>
              </div>
            </div>
            <div className = {
              st({
                display: 'flex',
                marginBottom: 'size-6',
                fontWeight: 'font-weight-5',
                fontSize: 'font-size-0',
                lineHeight: 'font-lineheight-0',
              })
            }>
              <div
                className = {
                  st({
                    flex: 'auto',
                    display: 'flex',

                  })
                }>
                <button 
                  className = {
                    st({
                      height: 'size-8',
                      paddingX: 'size-5',
                      fontWeight: 'font-weight-6',
                      borderRadius: 'radius-2',
                      background: 'black',
                      color: 'white'
                    })
                  } type="submit">
                  Buy now
                </button>
                <button 
                  className = {
                    st({
                      height: 'size-8',
                      paddingX: 'size-5',
                      fontWeight: 'font-weight-6',
                      borderRadius: 'radius-2',
                      borderWidth: 'border-size-1',
                      borderColor: 'gray-2',
                      color: 'gray-8',
                      background: 'white',
                    })
                  } type="button">
                  Add to bag
                </button>
              </div>
              <button
                className = {
                  st({
                    flex: 'none',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    width: 'size-7',
                    height: 'size-7',
                    borderRadius: 'radius-2',
                    color: 'gray-3',
                    borderWidth: 'border-size-1',
                    background: 'white',
                    borderColor: 'gray-2'
                  })
                } type="button" aria-label="Like">
                <svg width="20" height="20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" />
                </svg>
              </button>
            </div>
            <p 
            className = {
              st({
                fontSize: 'font-size-0',
                lineHeight: 'font-lineheight-0',
                color: 'gray-7'
              })
            }>
              Free shipping on all continental US orders.
            </p>
          </form>
        </div>
      </main>

    </div>
  )
}

export default Home
