import type { NextPage } from 'next'
import Head from 'next/head'
import { sprinklesTailwind as st, srOnly, clickable } from '../styles/sprinkles.css';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className = {
        st({
          display: 'flex',
          justifyContent: 'center',
          flexDirection: 'column',
          alignItems: 'center',
          background: 'gray-1',
          height: 'screen',
        })
      }>
        <h1>
          Tailwind Sprinkles
        </h1>
        <div 
        className = {
          st({
            display: 'flex',
            fontFamily: 'sans-serif',
            width: {
              tablet: 'size-content-3',
              mobile: 'size-auto'
            },
            marginY: 'size-auto',
            marginX: {
              tablet: 'size-auto',
              mobile: 'size-3',
            },
            background: {
             lightMode: 'white',
             darkMode: 'grape-9',
            },
            borderRadius: 'radius-3',
            boxShadow: 'shadow-2'
          })
        }>
          <div 
            className = {
              st({
                flex: 'none',
                width: 'size-12',
                height: 'size-13',
                position: 'relative',
              })
            }
            >
            <img src="/jacket.jpg" alt="" 
            loading="lazy" className = {
              st({
                position: 'absolute',
                width: {
                  tablet: 'full',
                  mobile: 'full'
                },
                height: {
                  tablet: 'full',
                  mobile: 'size-11'
                },
                objectFit: {
                  mobile: 'cover',
                  tablet: 'cover',
                },
                inset: '0'
              })}/>
          </div>
          <form 
            className = {
              st({
                flex: 'auto',
                padding: {
                  mobile: 'size-4',
                  tablet: 'size-5'
                }
              })
            }>
            <div
              className = {
                st({
                  display: {
                    mobile: 'flex',
                    tablet: 'flex'
                  },
                  flexWrap: {
                    mobile: 'wrap',
                    tablet: 'wrap'
                  },
                  paddingY: {
                    mobile: 'size-5'
                  }
                })
              }>
              <h1
                className = {
                  st({
                    flex: {
                      tablet: 'auto',
                      mobile: '1',
                    },
                    fontSize: 'font-size-2',
                    lineHeight: 'font-lineheight-4',
                    fontWeight: 'font-weight-6',
                    color: { 
                      lightMode: 'gray-9',
                      darkMode: 'gray-1',
                    },
                    marginY: {
                      tablet: 'size-0',
                      mobile: 'size-0',
                    }
                  })
                }>
                Yellow Rain Jacket
              </h1>
              <div 
                className = {
                  st({
                    fontSize: 'font-size-3',
                    lineHeight: 'font-lineheight-4',
                    fontWeight: 'font-weight-6',
                    color: { 
                      lightMode:  'gray-6',
                      darkMode:  'gray-2'
                    },
                  })
                }>
                $110.00
              </div>
              <div className = {
                st({
                  width: {
                    mobile: 'full',
                    tablet: 'full',
                  },
                  flex: 'none',
                  color: { 
                    lightMode:  'gray-7',
                    darkMode:  'gray-3',
                  },
                  fontWeight: 'font-weight-5',
                  fontSize: 'font-size-0',
                  lineHeight: 'font-lineheight-0',
                  marginTop: {
                    tablet: 'size-2',
                    mobile: 'size-2'
                  }
                })
              }>
                In stock
              </div>
            </div>
            <div 
              className = {
                st({
                  display: { 
                    mobile: 'flex',
                    tablet: 'flex',
                  },
                  marginTop: { 
                    mobile: 'size-4',
                    tablet: 'size-4',
                  },
                  marginBottom: { 
                    mobile: 'size-6',
                    tablet: 'size-6',
                  },
                  paddingBottom: { 
                    mobile: 'size-6',
                    tablet: 'size-6',
                  },
                  borderColor: { 
                    lightMode: 'gray-2',
                    darkMode: 'gray-8',
                  },
                  borderBottomWidth: 'border-size-1',
                  alignItems: 'baseline'
                })
              }>
              <div 
                className = {
                  st({
                    display: { 
                      mobile: 'flex',
                      tablet: 'flex',
                    },
                    fontSize: 'font-size-0',
                    lineHeight: 'font-lineheight-0',
                    gap: { 
                      mobile: 'size-2',
                      tablet: 'size-2'
                    },
                  })
                }>
                <label>
                  <input 
                    className = { srOnly }  name="size" type="radio" value="xs" checked />
                  <div
                    className = {
                      st({
                        width: { 
                          mobile: 'size-7',
                          tablet: 'size-7',
                        },
                        height: { 
                          mobile: 'size-7',
                          tablet: 'size-7',
                        },
                        borderRadius: 'radius-2',
                        display: { 
                          mobile: 'flex',
                          tablet: 'flex',
                        },
                        color: 'gray-1',
                        background: 'gray-9',
                        fontWeight: 'font-weight-7',
                        justifyContent: { 
                          mobile: 'center',
                          tablet: 'center',
                        },
                        alignItems: { 
                          mobile: 'center',
                          tablet: 'center'
                        },
                      })
                    }>
                    XS
                  </div>
                </label>
                <label>
                  <input className = { srOnly } name="size" type="radio" value="s" />
                  <div 
                    className = {
                      st({
                        width: { 
                          mobile: 'size-7',
                          tablet: 'size-7',
                        },
                        height: { 
                          mobile: 'size-7',
                          tablet: 'size-7',
                        },
                        borderRadius: 'radius-4',
                        display: { 
                          mobile: 'flex',
                          tablet: 'flex',
                        },
                        color: { 
                          lightMode: 'gray-7',
                          darkMode: 'gray-3',
                        },
                        justifyContent: { 
                          mobile: 'center',
                          tablet: 'center',
                        },
                        alignItems: { 
                          mobile: 'center',
                          tablet: 'center'
                        },
                      })
                    }>            
                    S
                  </div>
                </label>
                <label>
                  <input className = { srOnly } name="size" type="radio" value="m" />
                  <div 
                    className = {
                      st({
                        width: { 
                          mobile: 'size-7',
                          tablet: 'size-7',
                        },
                        height: { 
                          mobile: 'size-7',
                          tablet: 'size-7',
                        },
                        borderRadius: 'radius-4',
                        display: { 
                          mobile: 'flex',
                          tablet: 'flex',
                        },
                        color: { 
                          lightMode: 'gray-7',
                          darkMode: 'gray-3',
                        },
                        justifyContent: { 
                          mobile: 'center',
                          tablet: 'center',
                        },
                        alignItems: { 
                          mobile: 'center',
                          tablet: 'center'
                        },
                      })
                    }>            
                    M
                  </div>
                </label>
                <label>
                  <input className = { srOnly } name="size" type="radio" value="l" />
                  <div 
                     className = {
                      st({
                        width: { 
                          mobile: 'size-7',
                          tablet: 'size-7',
                        },
                        height: { 
                          mobile: 'size-7',
                          tablet: 'size-7',
                        },
                        borderRadius: 'radius-4',
                        display: { 
                          mobile: 'flex',
                          tablet: 'flex',
                        },
                        color: { 
                          lightMode: 'gray-7',
                          darkMode: 'gray-3',
                        },
                        justifyContent: { 
                          mobile: 'center',
                          tablet: 'center',
                        },
                        alignItems: { 
                          mobile: 'center',
                          tablet: 'center'
                        },
                      })
                    }>
                    L
                  </div>
                </label>
                <label>
                  <input className = { srOnly } name="size" type="radio" value="xl" />
                  <div 
                     className = {
                      st({
                        width: { 
                          mobile: 'size-7',
                          tablet: 'size-7',
                        },
                        height: { 
                          mobile: 'size-7',
                          tablet: 'size-7',
                        },
                        borderRadius: 'radius-4',
                        display: { 
                          mobile: 'flex',
                          tablet: 'flex',
                        },
                        color: { 
                          lightMode: 'gray-7',
                          darkMode: 'gray-3',
                        },
                        justifyContent: { 
                          mobile: 'center',
                          tablet: 'center',
                        },
                        alignItems: { 
                          mobile: 'center',
                          tablet: 'center'
                        },
                      })
                    }>                 
                    XL
                  </div>
                </label>
              </div>
            </div>
            <div className = {
              st({
                display: { 
                  mobile: 'flex',
                  tablet: 'flex',
                },
                flexDirection: {
                  mobile: 'column',
                  tablet: 'row'
                },
                gap: {
                  mobile: 'size-3'
                },
                marginBottom: { 
                  mobile: 'size-6',
                  tablet: 'size-6',
                },
                fontWeight: 'font-weight-5',
                fontSize: 'font-size-0',
                lineHeight: 'font-lineheight-0',
              })
            }>
              <div
                className = {
                  st({
                    flex: { 
                      mobile: 'auto',
                      tablet: 'auto',
                    },
                    flexDirection: {
                      mobile: 'column',
                      tablet: 'row'
                    },
                    display: { 
                      mobile: 'flex',
                      tablet: 'flex',
                    },
                    flexWrap: {
                      mobile: 'wrap',
                      tablet: 'nowrap'
                    },
                    gap: { 
                      mobile: 'size-3',
                      tablet: 'size-3'
                    },
                  })
                }>
                <button 
                  className = { clickable +  ' ' +  
                    st({
                      height: { 
                        mobile: 'size-8',
                        tablet: 'size-8',
                      },
                      width: {
                        tablet: 'size-auto',
                        mobile: 'full'
                      },
                      paddingX: { 
                        mobile: 'size-5',
                        tablet: 'size-5',
                      },
                      fontWeight: 'font-weight-6',
                      borderRadius: 'radius-2',
                      background: 'gray-9',
                      color: 'white'
                    })
                  } type="submit">
                  Buy now
                </button>
                <button 
                  className = {[
                    st({
                      height: { 
                        mobile: 'size-8',
                        tablet: 'size-8',
                      },
                      paddingX: { 
                        mobile: 'size-5',
                        tablet: 'size-5',
                      },
                      fontWeight: 'font-weight-6',
                      borderRadius: 'radius-2',
                      borderWidth: 'border-size-1',
                      borderColor: 'gray-2',
                      color: {
                        lightMode: 'gray-8',
                        darkMode: 'gray-4',
                      },
                      background: {
                       lightMode: 'white',
                       darkMode: 'grape-7',
                     },
                    }), clickable].join(' ')
                  } type="button">
                  Add to bag
                </button>
              </div>
              <button
                className = { clickable + ' ' +
                  st({
                    flex: { 
                      mobile: 'none',
                      tablet: 'none',
                    },
                    display: { 
                      mobile: 'flex',
                      tablet: 'flex',
                    },
                    alignItems: { 
                      mobile: 'center',
                      tablet: 'center',
                    },
                    justifyContent: { 
                      mobile: 'center',
                      tablet: 'center',
                    },
                    width: { 
                      mobile: 'full',
                      tablet: 'size-7',
                    },
                    height: { 
                      mobile: 'size-8',
                      tablet: 'size-7',
                    },
                    borderRadius: 'radius-2',
                    color: { 
                      lightMode: 'gray-3',
                      darkMode: 'gray-3',
                    },
                    borderWidth: 'border-size-1',
                    background: {
                       lightMode: 'white',
                       darkMode: 'grape-7',
                     },
                    borderColor: 'gray-2'
                  })
                } type="button" aria-label="Like">
                <svg width="20" height="20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" />
                </svg>
              </button>
            </div>
            <p 
            className = {
              st({
                fontSize: 'font-size-0',
                lineHeight: 'font-lineheight-0',
                color: { 
                  lightMode: 'gray-7',
                  darkMode: 'gray-2',
                },
                marginY: 'size-0'
              })
            }>
              Free shipping on all continental US orders.
            </p>
          </form>
        </div>
      </main>

    </div>
  )
}

export default Home
